spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homilux
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: 127.0.0.1
      port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: hani101003@gmail.com
    password: lzznxdnnqmqpcqdp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

homilux:
  jwt:
    base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
    access-token-expiration-minutes: 1
    refresh-token-expiration-days: 7
  upload-file:
    base-uri: file:///D:/IT/FullStackProject/upload/

vnpay:
  tmn-code: 0XSUQAMQ
  hash-secret: 1I3JASKUXS7JHX9XOGFPJZQ0LG46HDLG
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: https://e6bb-123-25-190-33.ngrok-free.app/api/v1/payments/callback